name: Feature Request
description: Suggest an enhancement or new feature for the RGB Badge project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of enhancement is this?
      options:
        - Hardware Design
        - Firmware/Software
        - Power Management
        - Manufacturing/Assembly
        - Documentation
        - Mechanical/Enclosure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions you've thought about

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Consider the impact on power consumption, cost, manufacturability, and complexity
      placeholder: |
        - Power consumption impact: ...
        - Cost impact: ...
        - Manufacturing complexity: ...
        - Performance impact: ...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing/validation
        - label: I can provide additional technical details

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, diagrams, or references
      placeholder: Links to similar implementations, datasheets, diagrams, etc.
