// Bad Apple Frame Data
// Auto-generated by bad_apple_converter.py
//
// Frame format: 10x10 monochrome
// Total frames: 6572
// Target FPS: 20

#ifndef BAD_APPLE_FRAMES_H
#define BAD_APPLE_FRAMES_H

#define BA_FRAME_COUNT 6572
#define BA_FPS 20
#define BA_WIDTH 10
#define BA_HEIGHT 10
#define BA_BYTES_PER_FRAME 13  // 100 pixels / 8 bits per byte = 12.5, rounded to 13
#define BA_FRAME_MS 50  // Milliseconds per frame

// File to load: bad_apple_frames.bin
// Use SPIFFS or LittleFS to store this file on ESP32
// File structure:
//   Header (6 bytes): num_frames(2), fps(1), width(1), height(1), padding(1)
//   Frames: 6572 frames × 13 bytes each

#endif // BAD_APPLE_FRAMES_H
